#!/usr/bin/env node
/**
 * flowd-codegen — emit a typed `.ts` contract from a compiled IR.
 *
 * Reads an IR JSON document (the `tools`/`types`/`flows` arrays) and
 * prints a self-contained TypeScript module: interfaces for the IR's
 * record/sum types, a typed `<Name>Tools` interface (camelCase methods),
 * and a `<Name>` class wrapping `Runtime` — registering under the IR's
 * snake_case tool names while exposing camelCase, fully-typed methods.
 *
 * This is the generator the README refers to; it is NOT a `flowc` flag.
 *
 *   node dist/codegen.js onboard.ir.json > onboard.flow.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";

interface Field {
  name: string;
  type: string;
}
interface Variant {
  name: string;
  fields: Field[];
}
interface TypeDecl {
  name: string;
  kind: "record" | "sum";
  fields?: Field[];
  variants?: Variant[];
}
interface Tool {
  name: string;
  input?: Field[];
  output: string;
  effect: { level: string };
}
interface Flow {
  name: string;
  params: { name: string; type: string }[];
  output: string;
}
interface Ir {
  ir_version: string;
  types?: TypeDecl[];
  tools?: Tool[];
  flows?: Flow[];
}

function tsType(irType: string): string {
  if (irType === "string") return "string";
  if (irType === "int" || irType === "float") return "number";
  if (irType === "bool") return "boolean";
  if (irType.startsWith("[") && irType.endsWith("]")) {
    return `Array<${tsType(irType.slice(1, -1))}>`;
  }
  return irType; // named user type → emitted interface/union
}

function camel(snake: string): string {
  return snake.replace(/_([a-z0-9])/g, (_m, c: string) => c.toUpperCase());
}

function pascal(s: string): string {
  const c = camel(s);
  return c.charAt(0).toUpperCase() + c.slice(1);
}

function fieldsObject(fields: Field[]): string {
  if (fields.length === 0) return "Record<string, never>";
  return (
    "{ " +
    fields.map((f) => `${f.name}: ${tsType(f.type)}`).join("; ") +
    " }"
  );
}

function emitTypeDecl(t: TypeDecl): string {
  if (t.kind === "record") {
    const body = (t.fields ?? [])
      .map((f) => `  ${f.name}: ${tsType(f.type)};`)
      .join("\n");
    return `export interface ${t.name} {\n${body}\n}`;
  }
  // sum → discriminated union matching the runtime's {variant, fields} encoding
  const arms = (t.variants ?? [])
    .map(
      (v) =>
        `  | { variant: ${JSON.stringify(v.name)}; fields: ${fieldsObject(v.fields)} }`,
    )
    .join("\n");
  return `export type ${t.name} =\n${arms};`;
}

export function generate(irJson: string, moduleSpecifier = "flowd"): string {
  const ir = JSON.parse(irJson) as Ir;
  if (typeof ir.ir_version !== "string" || !ir.ir_version.startsWith("1.")) {
    throw new Error(`unsupported IR ir_version ${String(ir.ir_version)}`);
  }
  const flow = (ir.flows ?? [])[0];
  if (!flow) throw new Error("IR has no flows");
  const Name = pascal(flow.name);

  const typeDecls = (ir.types ?? []).map(emitTypeDecl).join("\n\n");

  const toolSigs = (ir.tools ?? [])
    .map((t) => {
      const args = fieldsObject(t.input ?? []);
      return `  ${camel(t.name)}(args: ${args}): ${tsType(t.output)};`;
    })
    .join("\n");

  const toolWires = (ir.tools ?? [])
    .map(
      (t) =>
        `        ${JSON.stringify(t.name)}: (a) => impl.${camel(
          t.name,
        )}(a as never),`,
    )
    .join("\n");

  // Flow input type: the sole param's type, or a synthetic object.
  const inputType =
    flow.params.length === 1
      ? tsType(flow.params[0].type)
      : "{ " +
        flow.params.map((p) => `${p.name}: ${tsType(p.type)}`).join("; ") +
        " }";
  const outputType = tsType(flow.output);

  const flowNames = (ir.flows ?? []).map((f) => f.name);

  return `// Generated by flowd-codegen from a Flow IR. Do not edit by hand.
// Flows: ${flowNames.join(", ")}
import { Runtime, Suspension, type ProviderAdapter } from ${JSON.stringify(moduleSpecifier)};

${typeDecls ? typeDecls + "\n" : ""}
export interface ${Name}Tools {
${toolSigs}
}

const IR = ${JSON.stringify(irJson)};

export class ${Name} {
  private rt: Runtime;
  constructor(impl: ${Name}Tools, opts?: { traceDir?: string; implVersion?: string }) {
    this.rt = new Runtime(IR, {
      traceDir: opts?.traceDir,
      implVersion: opts?.implVersion,
      tools: {
${toolWires}
      },
    });
  }

  run(input: ${inputType}): ${outputType} | Suspension {
    return this.rt.run(input) as ${outputType} | Suspension;
  }

  resume(token: string, decision: unknown): ${outputType} | Suspension {
    return this.rt.resume(token, decision) as ${outputType} | Suspension;
  }

  /** Register a model provider adapter (the gateway's preferred path). */
  registerProvider(adapter: ProviderAdapter): void {
    this.rt.registerProvider(adapter);
  }

  /** Install a redactor that scrubs each value before the trace writer persists it. */
  setRedactor(fn: ((data: Buffer) => Buffer | null) | null): void {
    this.rt.setRedactor(fn);
  }

  close(): void {
    this.rt.close();
  }
}
`;
}

// CLI entry: node dist/codegen.js <ir.json> [moduleSpecifier]
if (require.main === module) {
  const file = process.argv[2];
  if (!file) {
    process.stderr.write("usage: flowd-codegen <ir.json> [moduleSpecifier]\n");
    process.exit(2);
  }
  const irJson = fs.readFileSync(path.resolve(file), "utf8");
  process.stdout.write(generate(irJson, process.argv[3]));
}
